name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "45 3 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: 'KAAYI4S'
          ICON_FIRST: "#41b883"
          ICON_SECOND: "#9effd3"
          BACKGROUND_FIRST: "#34495e"
          BACKGROUND_SECOND: "#41b883"
          LANG: "ja"
